version: '3.5'

services:
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - application
        restart: unless-stopped

networks:
    application:
        driver: bridge
        
volumes:
    postgres: