name: CI

on:
  push:
    branches:
    - main
    - release/*

jobs:
  build_utfpr_scan:
    runs-on: ubuntu-18.04
    env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'utfpr-scan' }}
        working-directory: ./backend/Utfpr.Api.Scan/Utfpr.Api.Scan
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Publish image
      run: |
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
      working-directory: ${{env.working-directory}}
