name: CI

on:
  push:
    branches:
    - main
    - release/*

jobs:
  build_utfpr_scan:
    runs-on: ubuntu-18.04
    steps:
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'utfpr-scan' }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set-up workdir
      working-directory: ./backend/Utfpr.Api.Scan/Utfpr.Api.Scan
      run: |
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
